### ISSUE TITLE
Add language detect code for multilingual abstracts.

### ISSUE THREAD

**Issue by rwarren2** [cldi/CanLink#18]
Will use Cavnar-style language detection from n-grams.

**Comment by rwarren2** [comment]
Sample TextCat implementation is here http://odur.let.rug.nl/~vannoord/TextCat/

The archive contains language models for unicode english and french. We'll just reimplement the perl script (tiny) in python and call it whenever an abstract has no language attached.

**Comment by rwarren2** [comment]
@maharshmellow Is this being done? Adding the appropriate xml:lang="xx" to each instance of an abstract?

**Comment by maharshmellow** [comment]
yes this is done. it looks like this `<bibo:abstract xml:lang="en">`
