### ISSUE TITLE
Wrong LOC author triple

### ISSUE THREAD

**Issue by rwarren2** [cldi/CanLink#31]
For a thesis, the predicate:

<rel:author rdf:resource="http://canlink.library.ualberta.ca/person/a1356bf027b49d1c35e3f3953690b118"/>

should actually be
<rel:aut rdf:resource="http://canlink.library.ualberta.ca/person/a1356bf027b49d1c35e3f3953690b118"/>

**Comment by maharshmellow** [comment]
whoops made a typo

**Comment by rwarren2** [comment]
The rel name space should be http://id.loc.gov/vocabulary/relators/  not http://purl.org/vocab/relationship/

**Comment by maharshmellow** [comment]
We have loc:pub and loc also has the namespace  http://id.loc.gov/vocabulary/relators/
Should I replace that with rel:pub?

**Comment by rwarren2** [comment]
rel:pub, rel:aut and rel:ths should all point to http://id.loc.gov/vocabulary/relators/
