### ISSUE TITLE
ontology nodes being re-created

### ISSUE THREAD

**Issue by rwarren2** [cldi/CanLink#34]
<rdf:Description rdf:about="http://canlink.library.ualberta.ca/ontologies/canlink#canlinkrepo">
    <doap:browse rdf:resource="http://github.com/cldi/CanLink"/>
  </rdf:Description>

This is being created by the python script but shouldn't be since it's in the ontology already.

Rule of thumb: If it's in the "http://canlink.library.ualberta.ca/ontologies/" path, the python script should not be creating it.

**Comment by maharshmellow** [comment]
I think I fixed this in e3effe0fd4e55e2007080c791f3e4d12d54c2fe7
