### ISSUE TITLE
Runtime Node Creation

### ISSUE THREAD

**Issue by rwarren2** [cldi/CanLink#35]
When creating the runtime node, can you change to the following structure:

To get the REVISION_NUMBER in python, run `git describe --all --long` in a shell at the start and keep the output.
To get the PID in python: use `os.getpid()`

  <rdf:Description rdf:about="http://canlink.library.ualberta.ca/runtime/3f17942b3e8e19cfc01a0284047c26f4">
 <rdf:type rdf:resource="http://www.w3.org/ns/prov#Activity"/>
 <rdf:type rdf:resource="http://www.w3.org/ns/prov#Generation"/>
    <prov:startedAtTime>2017-08-22T15:28:17Z</prov:startedAtTime>
    <void:inDataset rdf:resource="http://canlink.library.ualberta.ca/void/canlinkmaindataset"/>
    <prov:activity rdf:resource="http://canlink.library.ualberta.ca/ontologies/canlink#marclodconverter"/>
    <prov:endedAtTime>2017-08-22T15:28:38Z</prov:endedAtTime>
    <doap:revision>REVISION_NUMBER</doap:revision>
    <cldi:pid>PID</cldi:pid>
  <prov:actedOnBehalfOf  rdf:resource=""/>
  
  </rdf:Description>

**Comment by maharshmellow** [comment]
whats the namespace for cldi here?

**Comment by rwarren2** [comment]
http://canlink.library.ualberta.ca/ontologies/canlink#

so, http://canlink.library.ualberta.ca/ontologies/canlink#pid

I'll add this to the ontology.

**Comment by rwarren2** [comment]
Graph updated.
