### ISSUE TITLE
Create github issue programmatically when a new degree is created

### ISSUE THREAD

**Issue by rwarren2** [cldi/CanLink#37]
Referencing ticket #36  : 

When a degree is not in the bibo list:

http://purl.org/ontology/bibo/degrees/phd
http://purl.org/ontology/bibo/degrees/ma
http://purl.org/ontology/bibo/degrees/ms

 *and* is not already created in the dataset:

1. Reference the new degree as a url (eg: http://canlink.library.ualberta.ca/thesisDegree/llm)
1. Create a github ticket programmatically with title "new degree found: (with url)" and the specific thesis URL in the body of the ticket?

**Comment by maharshmellow** [comment]
How should I put the uri for the degree in the issue if we don't know what it is? In one of the records, it said the degree name was "Thesis." So for this would I create a link http://canlink.library.ualberta.ca/thesisDegree/thesis and then put it in the issue? 

Currently when I can't find a uri for the degree, I create a github issue with degree name as it appears in the records and then wait for someone to comment the proper uri. And then the program adds it to the database and processes the file. 

Or are you talking about making another issue after the person submits a uri for the degree?

**Comment by rwarren2** [comment]
"So for this would I create a link http://canlink.library.ualberta.ca/thesisDegree/thesis and then put it in the issue?" - I would omit that in that case and complain to github that we don't know the degree.

"Currently when I can't find a uri for the degree, I create a github issue with degree name as it appears in the records and then wait for someone to comment the proper uri. And then the program adds it to the database and processes the file." - That's what I was thinking of yes.
