### ISSUE TITLE
Make jango locations url relative

### ISSUE THREAD

**Issue by rwarren2** [cldi/CanLink#9]
When the webpage requests it's javascript and css it uses absolute urls that break proxying. 
eg: http://canlink.library.ualberta.ca/static/website/css/styles.css
Can you make it relative instead? 'static/website/css/styles.css' ?

You seem to be loading https://www.gstatic.com/recaptcha/api2/r20170712134223/recaptcha__en.js for some reason also?

Proxing is currently setup at http://canlink.library.ualberta.ca/submission, password sent through email.

**Comment by maharshmellow** [comment]
I just fixed the relative url problem in the latest commit. Where are the static files accessible on the server. I can't seem to find anything at http://canlink.library.ualberta.ca/submission/static/website/js/scripts.js

**Comment by rwarren2** [comment]
Fighting with this now.

**Comment by rwarren2** [comment]
Can you arrange it so that the landing page has a url instead of just / ?

**Comment by maharshmellow** [comment]
So locally I was running the landing page at http://127.0.0.1:8000/ 
Are you saying that I should move it to something like http://127.0.0.1:8000/submission/ ?

**Comment by rwarren2** [comment]
http://127.0.0.1:8000/submit.html would just fix it. And add:

 <base href="http://canlink.library.ualberta.ca/submission/">
To the <head> section of the html.

Can you so something similar for the thesisSubmission file?

**Comment by maharshmellow** [comment]
sorry but add what? :)

**Comment by rwarren2** [comment]
add  <base href="http://canlink.library.ualberta.ca/submission/"> to the <head> section.

**Comment by rwarren2** [comment]
Add `<basehref="http://canlink.library.ualberta.ca/submission/">` to the `<head>` section.

**Comment by maharshmellow** [comment]
Ok I added that. I can't seem to get it working at /submit.html but /submit works. Will that be ok? And should thesisSubmission go at /submit/thesisSubmission or just /thesisSubmission

**Comment by rwarren2** [comment]
Leave at thesisSubmission for now.

**Comment by rwarren2** [comment]
Did you push?

**Comment by maharshmellow** [comment]
ok it seems to be working locally. I just pushed it.

**Comment by rwarren2** [comment]
Ok. Working. It's posting to http://canlink.library.ualberta.ca/thesisSubmission/
Can you make it post to http://canlink.library.ualberta.ca/submission/thesisSubmission/ ?

**Comment by maharshmellow** [comment]
ok i pushed it.

**Comment by rwarren2** [comment]
[18/Jul/2017 22:17:07] "GET /static/website/fonts/NotoSans-Regular.ttf HTTP/1.1" 200 201644
Not Found: /thesisSubmission/
[18/Jul/2017 22:17:12] "POST /thesisSubmission/ HTTP/1.1" 404 2364

Bad endpoint?

**Comment by maharshmellow** [comment]
hmm thats weird. locally it shows 
[18/Jul/2017 22:11:06] "POST /submission/thesisSubmission/ HTTP/1.1" 200 5235

**Comment by rwarren2** [comment]
No you have to POST to /submission/thesisSubmission/
but the webpage has to answer /thesisSubmission/

**Comment by maharshmellow** [comment]
So the landing page is at /submit and I post to /submission/thesisSubmission and then the errors and success message is shown at /thesisSubmission ??

**Comment by rwarren2** [comment]
So.  landing page is at /submit, it's POST address in the html is /submission/thesisSubmission but the actual page in jango listens at /thesisSubmission

**Comment by maharshmellow** [comment]
I made a tiny change and pushed it. Not sure why its giving a post error though because I posted to /submission/thesisSubmission/ 
![screen shot 2017-07-18 at 4 35 07 pm](https://user-images.githubusercontent.com/4590693/28342857-a5000c36-6bd7-11e7-8991-6b25e190edf0.png)

**Comment by rwarren2** [comment]
18/Jul/2017 22:46:44] "POST /thesisSubmission/ HTTP/1.1" 200 136

It's posting to the right place, but then tries to load /thesisSubmission. What is your code doing then?

**Comment by maharshmellow** [comment]
Currently it shows the error messages at /thesisSubmission.

**Comment by rwarren2** [comment]
Right so it's posting to /submit/thesisSubmission which proxies to /thesisSubmission and then starts that view. 

That view is trying to load /thesisSubmission a second time, which fails because the proxy isn't picking it up. Can we talk  on skype?

**Comment by maharshmellow** [comment]
I redirect to /thesisSubmission after the processing is done with Python to display the html file. Call me whenever you are ready!

**Comment by rwarren2** [comment]
Switching over to native hosting.

**Comment by rwarren2** [comment]
Fixed by native hosting.
